## Day Objective
- Numpy library contin..

In [1]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

- np.full()
- np.ones()
- np.zeros()
- Reshaping
- Random methods
- Statistical operations

In [5]:
np.full(5,2)
## np.full(size, filled_value)

array([2, 2, 2, 2, 2])

In [6]:
np.full(5,'numpy')

array(['numpy', 'numpy', 'numpy', 'numpy', 'numpy'], dtype='<U5')

In [7]:
np.full([3,4],'Numpy')

array([['Numpy', 'Numpy', 'Numpy', 'Numpy'],
       ['Numpy', 'Numpy', 'Numpy', 'Numpy'],
       ['Numpy', 'Numpy', 'Numpy', 'Numpy']], dtype='<U5')

- **np.ones()**

In [9]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones(7, dtype = 'int')

array([1, 1, 1, 1, 1, 1, 1])

In [11]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones([4,4]).ndim

2

In [13]:
np.ones([3,3,2])
#   (3-d, rows, col)

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

- **np.zeros()**: Similar to np.ones()

- **Reshape**
    - We can modify the dimension of array

In [14]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a.ndim

1

In [15]:
len(a)

9

In [16]:
# 9 x 1
# 1 x 9
# 3 x 3

In [17]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a.reshape(3,3).ndim

2

In [20]:
b = np.array([[21,23,46,44,30],[66,12,99,39,3]])
b

array([[21, 23, 46, 44, 30],
       [66, 12, 99, 39,  3]])

In [21]:
len(b)

2

In [22]:
b.shape

(2, 5)

In [23]:
b.reshape(5,2)

array([[21, 23],
       [46, 44],
       [30, 66],
       [12, 99],
       [39,  3]])

In [24]:
## 1-d array to 3-d array

In [26]:
a2 = np.array([21,22,36,77,84,6])
a2

array([21, 22, 36, 77, 84,  6])

In [27]:
# 3 * 2,2 * 3, 6 * 1,6 * 6
a2.reshape(3,2)

array([[21, 22],
       [36, 77],
       [84,  6]])

In [28]:
a2.reshape(3,2).ndim

2

In [29]:
# 1 * 2 * 3
# 1 * 3 * 3
a2.reshape(3,2,1)

array([[[21],
        [22]],

       [[36],
        [77]],

       [[84],
        [ 6]]])

In [30]:
a2.reshape(3,2,1).ndim

3

### Statistical Operations

In [31]:
a3 = np.arange(10,30)
a3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [33]:
a = a3.reshape(4,5)
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [34]:
a.min()

10

In [35]:
a.max()

29

In [37]:
a.mean()

19.5

In [38]:
a.average()

AttributeError: 'numpy.ndarray' object has no attribute 'average'

In [39]:
np.average(a)

19.5

In [41]:
a.argmax() ## index of maximum value in the array

19

In [42]:
a.argmin()## index of minimum value in the array

0

In [44]:
a.sum()

390

- Note:
    - axis 0 --> col
    - axis 1 --> rows

In [45]:
np.min(a, 1)

array([10, 15, 20, 25])

In [46]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [47]:
np.exp(a)## Exponential value of each value in array

array([[2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10],
       [7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
        3.93133430e+12]])

In [48]:
np.sin(a)

array([[-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836],
       [-0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388]])

In [49]:
np.cos(a)

array([[-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722],
       [-0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462],
       [ 0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901],
       [ 0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753]])

In [50]:
np.tan(a)

array([[ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
         4.63021133e-01,  7.24460662e+00],
       [-8.55993401e-01,  3.00632242e-01,  3.49391565e+00,
        -1.13731371e+00,  1.51589471e-01],
       [ 2.23716094e+00, -1.52749853e+00,  8.85165604e-03,
         1.58815308e+00, -2.13489670e+00],
       [-1.33526407e-01,  1.17875355e+00, -3.27370380e+00,
        -2.81429605e-01,  8.87142844e-01]])

In [51]:
np.sqrt(a)

array([[3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949],
       [5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481]])

In [53]:
np.multiply(a,2)

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [54]:
np.power(a,2)

array([[100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576],
       [625, 676, 729, 784, 841]], dtype=int32)

In [55]:
help(np.power)

Help on ufunc object:

power = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array

### Random Methods

In [56]:
np.random.randint()

TypeError: randint() takes at least 1 positional argument (0 given)

In [60]:
np.random.randint(10)# integer value within the given range

6

In [65]:
np.random.randint(10,40)

19

In [69]:
np.random.randint(10,40,2)
##            (start,stop,no.of.values)

array([13, 17])

In [75]:
np.random.rand()# by default one value between 0 to 1

0.06787711611599068

In [76]:
np.random.rand(3,2)

array([[0.51057705, 0.61066345],
       [0.24486085, 0.66566929],
       [0.97311989, 0.20455607]])

In [78]:
np.random.random()## similar to rand()

0.9585393945123244

In [79]:
np.random.random(5)

array([0.01824794, 0.91336034, 0.04876985, 0.02834218, 0.18528347])

In [80]:
np.random.random(3,2)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [81]:
np.random.random([3,2])

array([[0.1718318 , 0.08620957],
       [0.15871831, 0.18565899],
       [0.64793986, 0.38713886]])

In [86]:
np.random.randn()# -ve to +ve values

-0.9018319762260183

In [87]:
np.random.randn(10)

array([-0.76987914,  0.0699536 ,  0.82150634,  0.0444049 , -0.41268403,
       -1.6695825 , -0.94290071,  1.13961796, -1.19110355,  0.00853988])

In [88]:
np.random.choice([1,2,3,4,5])

5

In [90]:
np.random.choice(['apssdc','machine','learning'])

'machine'

#### Accessing values in array

In [91]:
a1 = np.array([20,44,56,77])
a1

array([20, 44, 56, 77])

In [92]:
a1[1]

44

In [93]:
a1[-1]

77

In [94]:
a3 = np.array([[[23,4,56],[9,98,87]], [[41,12,22],[67,74,10]]])
a3

array([[[23,  4, 56],
        [ 9, 98, 87]],

       [[41, 12, 22],
        [67, 74, 10]]])

In [96]:
a3.ndim

3

In [95]:
a3[0]

array([[23,  4, 56],
       [ 9, 98, 87]])

In [97]:
a3[0].ndim

2

In [98]:
a3[0][1]

array([ 9, 98, 87])

In [99]:
a3[0][1][0]

9